server:
  port: 0

eureka:
  instance:
    preferIpAddress: true
    metadataMap:
      cluster: CLUSTER
  client:
    serviceUrl:
      defaultZone: http://192.168.25.15:8761/eureka/

spring:
  zipkin:
    baseUrl: http://192.168.25.15:9411/
    sender:
      type: web
  sleuth:
    web:
      skipPattern: ".*metrics.*"
    sampler:
      percentage: 1
    integration:
      enabled: false
feign:
  hystrix:
    enabled: true
