server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.8:8761/eureka/

hystrix.threadpool.default.coreSize: 100

spring.zipkin.baseUrl: http://192.168.0.8:9411/
spring.zipkin.sender.type: web
spring.sleuth.web.skipPattern: ".*metrics.*"

spring.sleuth.sampler.percentage: 1
spring.sleuth.integration.enabled: false
feign.hystrix.enabled: true

---
spring:
  profiles: docker
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

server:
  port: 8080
