 server:
  port: 8761

# Defines the Eureka server that is used by the Netflix OSS components to use as the registry
# for server discovery
eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 1
 
spring:
  #profiles: docker
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    baseUrl: http://localhost:9411/
