 server:
  port: 8765

eureka:
  instance:
    preferIpAddress: true
    metadataMap:
      cluster: CLUSTER
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  debug:
    request: true
  routes:
    card-service:
        path: /card-service/**
        serviceId: card-service
        stripPrefix: true
    statement-service:
        path: /statement-service/**
        serviceId: statement-service
        stripPrefix: true
    card-statement-composite:
        path: /card-statement-composite/**
        serviceId: card-statement-composite
        stripPrefix: true
        
spring:
  zipkin:
    baseUrl: http://localhost:9411/
    sender:
      type: web
  sleuth:
    web:
      skipPattern: ".*metrics.*"
    sampler:
      percentage: 1
    integration:
      enabled: false
