server:
  port: 0
turbine:
  amqp:
    port: 8989
  appConfig: card-service,statement-service,card-statement-composite,edge-server
  aggregator:
    clusterConfig: CLUSTER
  clusterNameExpression: metadata['cluster']
  combineHostPort: true 
    
turbine.aggregator.clusterConfig: CLUSTER
turbine.clusterNameExpression: metadata['cluster']
turbine.appConfig: card-service,statement-service,card-statement-composite,edge-server
turbine.stream.port: 8989
InstanceDiscovery.impl: com.netflix.turbine.discovery.EurekaInstanceDiscovery.class

---
spring:
  profiles: docker
  rabbitmq:
    host: 192.168.1.100
eureka: 
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

server:
  port: 8989
