  server:
  port: 9090
turbine:
  amqp:
    port: 9090
  appConfig: card-service,statement-service,card-statement-composite,edge-server
  aggregator:
    clusterConfig: CLUSTER
 # clusterNameExpression: metadata['cluster']
  combineHostPort: true 
    
turbine.aggregator.clusterConfig: CLUSTER
turbine.clusterNameExpression: metadata['cluster']
turbine.appConfig: card-service,statement-service,card-statement-composite,edge-server
turbine.stream.port: 9090
InstanceDiscovery.impl: org.springframework.cloud.netflix.turbine.EurekaInstanceDiscovery

---
spring:
  profiles: docker
  rabbitmq:
    host: 192.168.1.100
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

server:
  port: 9090
